apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: springboot-app
spec:
  replicas: 1

  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 30 }
        - setWeight: 100

  selector:
    matchLabels:
      app: springboot-app

  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: lakshmansai/springboot-app:13
          ports:
            - containerPort: 8080
